config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # ログイン後にリダイレクトするパスを設定
  devise_scope :user do
    # ログアウトパス
    get '/users/sign_out' => 'devise/sessions#destroy'
    resources :users, only: [:show]
  end

  root 'homes#index'
  # ログイン後、drinksにリダイレクト(application_controller参照)
  get 'generatedresult', to: 'generatedresults#new'
  post 'generatedresults', to: 'generatedresults#create'
  get 'generatedresults', to: 'generatedresults#show'
  resources :drinks, only: %i[index show]
  resource :profile, only: %i[show edit update]
  resources :bookmarks
  resources :socialsharings, only: %i[show index create]
  get 'posts/private', to: 'posts#private', as: 'private_posts'
  resources :posts do
    resource :favorites, only: %i[create destroy]
    collection do
      get 'search', to: 'posts#index', as: :search
      post 'search', to: 'posts#index', as: :search_post
    end
  end
  resources :tags do
    get :search, on: :collection
  end
  # メーラー用のurl
  Rails.application.routes.draw do
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end
  resources :notifications, only: %i[index]
  get 'contact', to: 'statics#contact'
  get 'terms_of_service', to: 'statics#terms_of_service'
  get 'privacy_policy', to: 'statics#privacy_policy'
  get 'items/search'   #楽天api用
end

app/models/favorite.rb
# frozen_string_literal: true

# 投稿に対するいいね機能のモデル
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

# 投稿に対するいいね機能のコントローラ
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @favorite = current_user.favorites.new(post_id: @post.id)
    @favorite.save
    @post.create_notification_favorite!(current_user)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to posts_path }
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @favorite = current_user.favorites.find_by(post_id: @post.id)
    @favorite.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to posts_path }
    end
  end
end

app/views/favorites/_favorite.html.erb
<div id="favorite_<%= post.id %>">
    <% if post.favorited_by?(current_user) %>
      <%= link_to post_favorites_path(post), data: { turbo_method: :delete } do %>
        <i class="fa-solid fa-heart" style="color: #f04769;"></i>
        <% if post.favorites.count > 0 %>
          <%= post.favorites.count %>いいね
        <% else %>
          いいね
        <% end %>
      <% end %>
    <% else %>
      <%= link_to post_favorites_path(post), data: { turbo_method: :post } do %>
        <i class="fa-regular fa-heart fa-sm"></i>
        <% if post.favorites.count > 0 %>
          <%= post.favorites.count %>いいね
        <% else %>
          いいね
        <% end %>
      <% end %>
    <% end %>
</div>

app/views/favorites/create.turbo_stream.erb
<%= turbo_stream.replace "favorite_#{@post.id}",
                        partial: "favorites/favorite",
                        locals: { post: @post } %>

app/views/favorites/destroy.turbo_stream.erb
<%= turbo_stream.replace "favorite_#{@post.id}",
                        partial: "favorites/favorite",
                        locals: { post: @post } %>