config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # ログイン後にリダイレクトするパスを設定
  devise_scope :user do
    # ログアウトパス
    get '/users/sign_out' => 'devise/sessions#destroy'
    resources :users, only: [:show]
  end

  root 'homes#index'
  # ログイン後、drinksにリダイレクト(application_controller参照)
  get 'generatedresult', to: 'generatedresults#new'
  post 'generatedresults', to: 'generatedresults#create'
  get 'generatedresults', to: 'generatedresults#show'
  resources :drinks, only: %i[index show]
  resource :profile, only: %i[show edit update]
  resources :bookmarks
  resources :socialsharings, only: %i[show index create]
  get 'posts/private', to: 'posts#private', as: 'private_posts'
  resources :posts do
    resource :favorites, only: %i[create destroy]
    collection do
      get 'search', to: 'posts#index', as: :search
      post 'search', to: 'posts#index', as: :search_post
    end
  end
  resources :tags do
    get :search, on: :collection
  end
  # メーラー用のurl
  Rails.application.routes.draw do
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end
  resources :notifications, only: %i[index]
  get 'contact', to: 'statics#contact'
  get 'terms_of_service', to: 'statics#terms_of_service'
  get 'privacy_policy', to: 'statics#privacy_policy'
  get 'items/search'   #楽天api用
end

app/views/shared/_footer.html.erb
<!-- お問い合わせ関連　-->
<footer class="footer footer-center p-8 text-gray-400 bg-teal-950">
    <nav class="grid grid-flow-col gap-3">
      <%= link_to '利用規約', terms_of_service_path %>
      <%= link_to 'お問い合わせ', contact_path %>
      <%= link_to 'プライバシーポリシー', privacy_policy_path %>
    </nav> 
</footer>

app/views/shared/_google_logged_in.html.erb
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to omniauth_authorize_path(resource_name, provider), data: { turbo: false }, class: "google-auth-button" do %>
      <!-- カスタムボタンのHTMLを挿入 -->
      <div class="btn font-roboto bg-white text-black border-black">
        <div class="gsi-material-button-content-wrapper">
          <div class="gsi-material-button-icon" style="display: inline-block; vertical-align: middle; width: 24px; height: 24px;">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: block; width: 24px; height: 24px;">
            <!-- SVGコード -->
              <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
              <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
              <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
              <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
              <path fill="none" d="M0 0h48v48H0z"></path>
            </svg>
          </div>
          <span class="gsi-material-button-contents p-2" style="display: inline-block; vertical-align: middle;">Googleで続行</span>
        </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_header_logged_in.html.erb
<!-- ナビゲーションバー(ログイン中) -->
<header>
  <div class="drawer z-20 relative">
    <input id="my-drawer-3" type="checkbox" class="drawer-toggle" /> 
    <div class="drawer-content">
      <!-- Navbar -->
      <div class="w-full navbar bg-white justify-between"> 
        <div class="flex-none ">
          <label for="my-drawer-3" aria-label="open sidebar" class="btn btn-square btn-ghost">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
          </label>
      </div> 
      <div class="flex-1 px-2 mx-2 max-sm:hidden">
        <%= link_to root_path do %>
          <%= image_tag 'kotonoha_logo.png',size: '170x170' , class: " object-cover transition duration-500 ease-in-out transform hover:scale-105" %>
        <% end %>
      </div>
        <%= form_with url: generatedresults_path, method: :get, local: true, id: 'drink-search-form' do |form| %>
          <%= form.text_field :keyword, placeholder: "ドリンク名を入力", class: "text-sm text-green-700 border border-emerald-700 bg-slate-50 input input-bordered input-md w-full max-w-lg" %>
          <%= form.submit "作成", class: "btn btn-primary" %>
        <% end %>
        <div class="flex-none hidden md:block">
          <ul class="menu menu-horizontal">
            <!-- Navbar menu content here -->
            <li>
              <a href="<%= posts_path %>">
                <i class="fa-solid fa-pen fa-sm"></i>投稿一覧
              </a>
            </li>
            <li>
              <a href="<%= drinks_path %>">
                <i class="fa-solid fa-book-open fa-sm "></i>メニュー表
              </a>
            </li>
          </ul>
        </div>
        <div class="tooltip tooltip-bottom" data-tip="Share">
          <%= link_to socialsharings_path, class: "btn bg-indigo-500 hover:bg-indigo-600 text-white ml-2" do %>
            <i class="fa-solid fa-champagne-glasses fa-sm"></i>
          <% end %>
        </div>
      </div>
    </div> 
    <div class="drawer-side z-20	z-index: 20;">
      <label for="my-drawer-3" aria-label="close sidebar" class="drawer-overlay"></label> 
      <ul class="menu p-4 w-80 min-h-full bg-stone-300">
        <!-- Sidebar content here -->
        <li>
        <a href="<%= root_path %>">
          <i class="fa-solid fa-house fa-sm"></i>ホーム
        </a>
        </li>
        <li>
          <a href="<%= drinks_path %>">
            <i class="fa-solid fa-book-open fa-sm"></i>メニュー表
          </a>
        </li>
        <li>
          <a href="<%= bookmarks_path %>">
          <i class="fa-regular fa-bookmark fa-sm"></i>保存したドリンク
          </a>
        </li>
        <li>
          <a href="<%= generatedresult_path %>">
            <i class="fa-solid fa-bell-concierge fa-sm"></i>ドリンクを注文する
          </a>
        </li>
        <li>
            <a href="<%= posts_path %>">
            <i class="fa-solid fa-pen fa-sm"></i>投稿一覧
          </a>
        </li>
        <li>
            <a href="<%= profile_path %>">
            <i class="fa-solid fa-gear fa-sm"></i>設定・通知
          </a>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa-solid fa-right-from-bracket fa-sm"></i>ログアウト
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_header_logged_out.html.erb
<!-- ナビゲーションバー(ログイン前) -->
<header>
  <div class="drawer z-20 relative">
    <input id="my-drawer-3" type="checkbox" class="drawer-toggle" /> 
    <div class="drawer-content">
      <!-- Navbar -->
      <div class="w-full navbar bg-white justify-between"> 
        <div class="flex-none ">
          <label for="my-drawer-3" aria-label="open sidebar" class="btn btn-square btn-ghost">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
          </label>
      </div> 
      <div class="flex-1 px-2 mx-2 max-sm:hidden">
        <%= link_to root_path do %>
          <%= image_tag 'kotonoha_logo.png',size: '170x170' , class: " object-cover transition duration-500 ease-in-out transform hover:scale-105" %>
        <% end %>
      </div>
        <%= form_with url: generatedresults_path, method: :get, local: true, id: 'drink-search-form' do |form| %>
          <%= form.text_field :keyword, placeholder: "ドリンク名を入力", class: "text-sm text-green-700 border border-emerald-700 bg-slate-50 input input-bordered input-md w-full max-w-lg" %>
          <%= form.submit "作成", class: "btn btn-primary" %>
        <% end %>
        <div class="flex-none hidden md:block">
          <ul class="menu menu-horizontal">
            <!-- Navbar menu content here -->
            <li>
              <a href="<%= posts_path %>">
                <i class="fa-solid fa-pen fa-sm"></i>投稿一覧
              </a>
            </li>
            <li>
              <a href="<%= drinks_path %>">
                <i class="fa-solid fa-book-open fa-sm "></i>メニュー表
              </a>
            </li>
          </ul>
        </div>
        <div class="tooltip tooltip-bottom" data-tip="Share">
          <%= link_to socialsharings_path, class: "btn bg-indigo-500 hover:bg-indigo-600 text-white ml-2" do %>
            <i class="fa-solid fa-champagne-glasses fa-sm"></i>
          <% end %>
        </div>
      </div>
    </div> 
    <div class="drawer-side z-20	z-index: 20;">
      <label for="my-drawer-3" aria-label="close sidebar" class="drawer-overlay"></label> 
      <ul class="menu p-4 w-80 min-h-full bg-stone-300">
        <!-- Sidebar content here -->
        <li>
        <a href="<%= root_path %>">
          <i class="fa-solid fa-house fa-sm"></i>ホーム
        </a>
        </li>
        <li>
          <a href="<%= drinks_path %>">
            <i class="fa-solid fa-book-open fa-sm"></i>メニュー表
          </a>
        </li>
        <li>
          <a href="<%= posts_path %>">
            <i class="fa-solid fa-pen fa-sm"></i>投稿一覧
          </a>
        </li>
        <li>
          <a href="<%= new_user_session_path %>">
            <i class="fa-solid fa-right-to-bracket fa-sm "></i>ログイン
          </a>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_loading.html.erb
<div id="modalOverlay" class="hidden fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-40">
  <div id="loadingModal" class="max-w-md mx-auto bg-white rounded-lg z-50">
    <div class="animate-pulse text-center text-purple-600 p-4">
      読み込み中
    </div>
    <div class="animate-pulse flex justify-center p-4 py-10" >
      <div class="animate-ping h-4 w-4 bg-purple-600 rounded-full"></div>
      <div class="animate-ping h-4 w-4 bg-purple-600 rounded-full mx-6"></div>
      <div class="animate-ping h-4 w-4 bg-purple-600 rounded-full"></div>
    </div>
    <div class="text-center p-4">
      <p class ="p-4 text-purple-600">Thank you !</p>
      ドリンクを作ってるじょ</br>
      ちょっと待つじょ</br>
    </div>
      <%= image_tag 'kotonoha_okozyo.png', class: "animate-pulse p-12 max-w-md mx-auto",size: '200x200'%>
  </div>
</div>

app/views/shared/_sharingbutton.html.erb
<%= form_with model: Socialsharing.new, url: socialsharings_path, local: true, id: "socialsharing-form", class: "socialsharing-form p-2" do |form| %>
  <%= form.hidden_field :generated_drink, value: @generated_results[:drink_name] %>
  <%= form.hidden_field :generated_word, value: @generated_results[:drink_word] %>
  <%= form.hidden_field :generated_info, value: @generated_results[:drink_info] %>
  <%= form.hidden_field :image, value: @image %>
  <!-- シェアボタン -->
  <button type="submit" class="btn bg-indigo-500 hover:bg-indigo-600 text-white">
    <i class="fa-solid fa-champagne-glasses fa-sm"></i>ドリンクをシェア
  </button>
<% end %>