config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # ログイン後にリダイレクトするパスを設定
  devise_scope :user do
    # ログアウトパス
    get '/users/sign_out' => 'devise/sessions#destroy'
    resources :users, only: [:show]
  end

  root 'homes#index'
  # ログイン後、drinksにリダイレクト(application_controller参照)
  get 'generatedresult', to: 'generatedresults#new'
  post 'generatedresults', to: 'generatedresults#create'
  get 'generatedresults', to: 'generatedresults#show'
  resources :drinks, only: %i[index show]
  resource :profile, only: %i[show edit update]
  resources :bookmarks
  resources :socialsharings, only: %i[show index create]
  get 'posts/private', to: 'posts#private', as: 'private_posts'
  resources :posts do
    resource :favorites, only: %i[create destroy]
    collection do
      get 'search', to: 'posts#index', as: :search
      post 'search', to: 'posts#index', as: :search_post
    end
  end
  resources :tags do
    get :search, on: :collection
  end
  # メーラー用のurl
  Rails.application.routes.draw do
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end
  resources :notifications, only: %i[index]
  get 'contact', to: 'statics#contact'
  get 'terms_of_service', to: 'statics#terms_of_service'
  get 'privacy_policy', to: 'statics#privacy_policy'
  get 'items/search'   #楽天api用
end

app/models/post.rb
# frozen_string_literal: true

# 投稿のモデル
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  # socialsharing外部インスタンス➡️postにパラメータを渡してtag_nameに新しい値を入れるためメソッド追加
  attr_accessor :tag_names

  belongs_to :user
  has_many :posttags, dependent: :destroy
  has_many :tags, through: :posttags
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :body, presence: true
  validates :visibility, presence: true

  enum visibility: { 非公開: 0, 公開: 1 }

  # 現在ログインしているユーザーによっていいねされてる？
  def favorited_by?(user)
    # いいねは存在してる？(いいねを既に押してるか、押していないか)
    favorites.exists?(user_id: user.id)
  end

  # Ransackによる検索可能な属性を定義
  def self.ransackable_attributes(_auth_object = nil)
    %w[body created_at id user_id visibility]
  end

  # タグ名で検索可能にするためのメソッド
  def self.ransackable_associations(_auth_object = nil)
    ['tags']
  end

  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id,
                               user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    return if temp.present?

    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: 'favorite'
    )
    # 自分の投稿に対するいいねの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# 投稿のコントローラ
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  # 公開時の投稿を表示
  def index
    @post = current_user.posts.new
    @q = Post.ransack(params[:q])
    # タグとユーザーを事前に読み込み（N+1防止）
    @posts = @q.result.includes(:tags, :user).where(visibility: Post.visibilities[:公開]).order(created_at: :desc)
  end

  def private
    @post = current_user.posts.new
    @q = Post.ransack(params[:q])
    # タグとユーザーを事前に読み込み（N+1防止）
    @private_posts = @q.result.includes(:tags, :user).where(visibility: Post.visibilities[:非公開]).order(created_at: :desc)
  end

  def show
  end

  # 新規投稿ページの表示
  def new
    @q = current_user.posts.ransack(params[:q])
    # 非公開投稿を取得
    @private_posts = @q.result.where(visibility: Post.visibilities[:非公開]).order(created_at: :desc)
    @post = current_user.posts.new
    @post.tag_names = params[:tag_names] if params[:tag_names].present?
    @post.body = params[:body] if params[:body].present?
    @post.drink_word = params[:drink_word] if params[:drink_word].present?
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)
    # モデルにないのでtagを直接取得
    tag_names = params[:post][:tag_names]

    if @post.body.blank?
      flash[:alert] = '本文を入力してください。'
      redirect_to new_post_path
      return # 以降の処理は実行しない
    end

    if @post.save
      # タグがあれば追加
      add_tags(tag_names) if tag_names.present?

      if @post.visibility == '非公開'
        redirect_to  private_posts_path
      else
        # 公開投稿の場合のリダイレクト
        redirect_to posts_path
      end
    else
      render :new
    end
  end

  def update
  end

  def destroy
    if @post.destroy
      if @post.visibility == '公開'
        redirect_to posts_path
      else
        redirect_to  private_posts_path
      end
    else
      redirect_to @post
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  # タグの作成と投稿への追加
  def create_tags(post, tags)
    tags.each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name)
      post.tags << tag unless post.tags.include?(tag)
    end
  end

  def post_params
    params.require(:post).permit(:body, :image, :image_cache, :drink_word, :visibility).merge(visibility: params[:post][:visibility].to_i)
  end

  # タグが指定されている場合にタグを追加
  def add_tags(tag_names)
    tags = tag_names.split(/[、,]+/).map(&:strip).uniq
    create_tags(@post, tags)
  end

  def blank
    return if @post.body.blank?
  end
end

app/views/posts/_new.html.erb
<%= render "shared/loading" %>
<div class="flex flex-col sm:flex-row ">
    <!-- 新規投稿フォーム -->
    <div class="min-h-screen bg-gray-100 flex items-center justify-center w-11/12 mx-auto max-w-screen-xl">
      <div class="container mx-auto max-w-md shadow-md hover:shadow-lg transition duration-300">
        <div class="py-8 p-8 bg-white rounded-xl">
          <div class="mb-6 text-center">
            <h1 class="text-xl text-gray-700 font-semibold">本日の一杯</h1>
          </div>
          <%= form_with(model: @post, local: true, class: "space-y-5") do |form| %>
            <% if @post.visibility == '非公開' %>
              <%= hidden_field_tag :turbo_frame, "private_posts" %>
            <% end %>
            <div>
              <%= form.label :tag_names, "タグ", class: "block text-gray-700 font-medium mb-2" %>
              <%= form.text_field :tag_names, value: @post.tag_names || params[:tag_names], placeholder: "例）お酒,ビール", class: "input input-bordered w-full max-w-xs" %>
            </div>

            <div class="form-group mb-3"">
                <%= form.label :image, '画像' %>
                <%= form.file_field :image, class:'form-control js-file-select-preview', accept: 'image/*', data: { target: '#preview-target' } %>
                <%= form.hidden_field :image_cache %>
            </div>
            <div class="form-group mt-3 mb-3">
              <% if @post.image.present? %>
                <%= image_tag @post.image.url %>
              <% else %>
                <%= image_tag 'kotonoha_bookmark.png',id: 'preview-target',size: '150x150' %>
              <% end %>
            </div>

            <div>
              <%= form.label :drink_word, "ドリンク言葉", class: "block text-gray-700 font-medium mb-2" %>
              <%= form.text_field :drink_word, rows: 4, value: @post.drink_word || params[:drink_word] ,placeholder: "ドリンク言葉",class: "w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none focus:border-blue-500" %>
            </div>

            <div>
              <%= form.label :body, "投稿内容", class: "block text-gray-700 font-medium mb-2" %>
              <%= form.text_area :body, rows: 4, value: @post.body || params[:body] ,placeholder: "本日の一杯を投稿してみましょう。何を飲んだ？",class: "w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none focus:border-blue-500" %>
            </div>
            <fieldset class="mt-4">
              <legend class="text-gray-700 font-medium mb-2">公開設定</legend>
              <div class="flex items-center">
                <label class="flex items-center">
                  <%= form.radio_button :visibility, 0, checked: @post.visibility == '非公開', class: "radio mr-2" %>
                  <span class="label-text">非公開</span>
                </label>
                <label class="flex items-center mr-4">
                  <%= form.radio_button :visibility, 1, checked: @post.visibility == '公開', class: "radio mr-2" %>
                  <span class="label-text">公開</span>
                </label>
              </div>
            </fieldset>
            <div class="flex justify-center mt-6">
              <%= form.submit "投稿する", class: "btn btn-primary w-full mt-4" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/posts/index.html.erb
<head>
  <script>
    function openNewPostModal() {
      var modal = document.getElementById('new_post_modal');
      modal.showModal();
    }

    function closeNewPostkModal() {
      var modal = document.getElementById('new_post_modal');
      modal.close();
    }
  </script>
</head>

<div class="min-h-screen flex flex-wrap items-center justify-center bg-gray-100">
  <%= render "shared/loading" %>
  <!-- Your existing content here -->
  <div class="w-full max-w-2xl p-4 bg-white shadow-lg rounded-lg">
    <h1 class="text-center text-2xl p-4 text-gray-700 font-semibold">本日の一杯をシェアしよう</h1>
    <p class="text-center text-green-700">※タグをクリックで商品検索ができます。</p>
    <div class="p-4 bg-stone-300 sticky top-0 z-10">
      <%= search_form_for @q, class: "form-control flex flex-col gap-4" do |f| %>
        <div class="flex gap-2 items-center">
          <div data-controller="autocomplete" data-autocomplete-url-value="/tags/search" role="combobox" class="flex-grow">
            <%= f.search_field :tags_name_cont, data: { autocomplete_target: 'input' }, placeholder: "タグで検索", class: "input input-bordered input-primary w-full" %>
            <%= f.hidden_field :tags_name, data: { autocomplete_target: 'hidden' } %>
            <ul class="list-group bg-white absolute w-full md:text-sm max-w-xs" data-autocomplete-target="results"></ul>
          </div>
          <%= f.submit "検索", class: "btn btn-primary" %>
          <div class="tooltip tooltip-bottom" data-tip="新規投稿">
            <%= link_to "javascript:void(0);", onclick: "openNewPostModal()", class: "ml-auto btn btn-outline text-white bg-indigo-500 hover:bg-indigo-600" do %>
              <i class="fa-regular fa-square-plus fa-sm"></i>
            <% end %>
          </div>
          <div class="tooltip tooltip-bottom" data-tip="非公開">
            <%= link_to private_posts_path, class: "ml-auto btn btn-outline text-white bg-indigo-700 hover:bg-indigo-800" do %>
              <i class="fa-solid fa-unlock fa-sm"></i>
            <% end %>
          </div> 
        </div>
      <% end %>
    </div>
    <!-- モーダル -->
    <div class="text-left">
      <dialog id="new_post_modal" class="modal">
        <div class="modal-box">
          <form method="dialog">
            <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2" onclick="closeNewPostkModal()">✕</button>
          </form>
          <%= render 'posts/new' %>
        </div>
      </dialog>
    </div>
    <div class="mt-4">
      <% @posts.each do |post| %>
        <div class="p-4 my-2 bg-gray-50 rounded-lg shadow">
          <div class="flex items-center gap-4 mb-4">
            <div class="avatar">
              <div class="w-12 h-12 rounded-full">
                <%= image_tag post.user.avatar.url %>
              </div>
            </div>
            <div>
              <div class="font-bold"><%= post.user.name %></div>
              <time class="text-xs text-gray-500"><%= l post.created_at, format: :short %></time>
            </div>
            <% if current_user == post.user %>
              <%= link_to post_path(post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "ml-auto btn btn-outline btn-sm" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
          <div class="flex flex-wrap gap-2 mb-4">
            <% post.tags.each do |tag| %>
              <span class="badge badge-primary badge-outline mr-2">
                <%= link_to items_search_path(keyword: tag.name)  do %>
                  <%= tag.name %>
                <% end %>
              </span>
            <% end %>
            <% if post.drink_word.present? %>
              <span class="badge text-violet-700 badge-outline mr-2">
                <%= post.drink_word %>
              </span>
            <% end %>
          </div>
          <% if post.image.present? %>
            <div class="mb-4 flex justify-center">
              <%= image_tag post.image.url, alt: "#{post.image}の画像", class: "aspect-square w-50 h-50 object-cover rounded-lg" %>
            </div>
          <% end %>
          <div class="text-gray-700"><%= post.body %></div>
          <%= render 'favorites/favorite', post: post %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render "shared/loading" %>
<div class="flex flex-col sm:flex-row ">
  <div class="new-post-form w-full sm:w-1/2">
    <!-- 新規投稿フォーム -->
    <div class="min-h-screen bg-gray-100 flex items-center justify-center w-11/12 mx-auto max-w-screen-xl">
      <div class="container mx-auto max-w-md shadow-md hover:shadow-lg transition duration-300">
        <div class="py-8 p-8 bg-white rounded-xl">
          <div class="mb-6 text-center">
            <h1 class="text-xl text-gray-700 font-semibold">本日の一杯</h1>
          </div>
          <%= form_with(model: @post, local: true, class: "space-y-5") do |form| %>
            <% if @post.visibility == '非公開' %>
              <%= hidden_field_tag :turbo_frame, "private_posts" %>
            <% end %>
            <div>
              <%= form.label :tag_names, "タグ", class: "block text-gray-700 font-medium mb-2" %>
              <%= form.text_field :tag_names, value: @post.tag_names || params[:tag_names], placeholder: "例）お酒,ビール", class: "input input-bordered w-full max-w-xs" %>
            </div>

            <div class="form-group mb-3"">
                <%= form.label :image, '画像' %>
                <%= form.file_field :image, class:'form-control js-file-select-preview', accept: 'image/*', data: { target: '#preview-target' } %>
                <%= form.hidden_field :image_cache %>
            </div>
            <div class="form-group mt-3 mb-3">
              <% if @post.image.present? %>
                <%= image_tag @post.image.url %>
              <% else %>
                <%= image_tag 'kotonoha_bookmark.png',id: 'preview-target',size: '150x150' %>
              <% end %>
            </div>

            <div>
              <%= form.label :drink_word, "ドリンク言葉", class: "block text-gray-700 font-medium mb-2" %>
              <%= form.text_field :drink_word, rows: 4, value: @post.drink_word || params[:drink_word] ,placeholder: "ドリンク言葉",class: "w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none focus:border-blue-500" %>
            </div>

            <div>
              <%= form.label :body, "投稿内容", class: "block text-gray-700 font-medium mb-2" %>
              <%= form.text_area :body, rows: 4, value: @post.body || params[:body] ,placeholder: "本日の一杯を投稿してみましょう。何を飲んだ？",class: "w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none focus:border-blue-500" %>
            </div>
            <fieldset class="mt-4">
              <legend class="text-gray-700 font-medium mb-2">公開設定</legend>
              <div class="flex items-center">
                <label class="flex items-center">
                  <%= form.radio_button :visibility, 0, checked: @post.visibility == '非公開', class: "radio mr-2" %>
                  <span class="label-text">非公開</span>
                </label>
                <label class="flex items-center mr-4">
                  <%= form.radio_button :visibility, 1, checked: @post.visibility == '公開', class: "radio mr-2" %>
                  <span class="label-text">公開</span>
                </label>
              </div>
            </fieldset>
            <div class="flex justify-center mt-6">
              <%= form.submit "投稿する", class: "btn btn-primary w-full mt-4" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="private-posts-list w-full sm:w-1/2">
    <%= render 'private_posts', private_posts: @private_posts %>
    <div class=" p-6 text-right">
      <%= search_form_for @q, url: new_post_path, class: "form-control" do |f| %>
        <div class="flex gap-2 items-center">
          <div data-controller="autocomplete" data-autocomplete-url-value="/tags/search" role="combobox">
            <%= f.search_field :tags_name_cont,data: { autocomplete_target: 'input' },placeholder: "タグで検索" ,class: "input input-bordered input-primary w-full max-w-xs" %>
            <%= f.hidden_field :tags_name, data: { autocomplete_target: 'hidden' } %>
            <ul class="list-group bg-white absolute w-full md:text-sm max-w-max" data-autocomplete-target="results"></ul>
            <div class="absolute inset-y-0 left-0 flex items-center pointer-events-none pl-4"></div>
          </div>
          <%= f.submit "検索", class: "btn btn-primary" %>
        </div>
      <% end %>
      <div class="p-2">
        <%= link_to posts_path, class: "btn bg-indigo-500 hover:bg-indigo-600 text-white" do %>
          <i class="fa-regular fa-comments fa-sm"></i>
          みんなの投稿
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/private.html.erb
<head>
  <script>
    function openNewPostModal() {
      var modal = document.getElementById('new_post_modal');
      modal.showModal();
    }

    function closeNewPostkModal() {
      var modal = document.getElementById('new_post_modal');
      modal.close();
    }
  </script>
</head>

<div class="min-h-screen flex flex-wrap items-center justify-center bg-gray-100">
  <%= render "shared/loading" %>
  <div class="w-full max-w-2xl p-4 bg-white shadow-lg rounded-lg">
    <h1 class="text-center text-2xl p-4 text-gray-700 font-semibold">非公開投稿</h1>
    <div class="p-4 bg-stone-300 sticky top-0 z-10">
      <%= search_form_for @q, url: private_posts_path, class: "form-control flex flex-col gap-4" do |f| %>
        <div class="flex gap-2 items-center">
          <div data-controller="autocomplete" data-autocomplete-url-value="/tags/search" role="combobox" class="flex-grow">
            <%= f.search_field :tags_name_cont,data: { autocomplete_target: 'input' },placeholder: "タグで検索" ,class: "input input-bordered input-primary w-full" %>
            <%= f.hidden_field :tags_name, data: { autocomplete_target: 'hidden' } %>
            <ul class="list-group bg-white absolute w-full md:text-sm max-w-xs" data-autocomplete-target="results"></ul>
          </div>
          <%= f.submit "検索", class: "btn btn-primary" %>
          <div class="tooltip tooltip-bottom" data-tip="新規投稿">
            <%= link_to "javascript:void(0);", onclick: "openNewPostModal()", class: "ml-auto btn btn-outline text-white bg-indigo-500 hover:bg-indigo-600" do %>
              <i class="fa-regular fa-square-plus fa-sm"></i>
            <% end %>
          </div>
          <div class="tooltip tooltip-bottom" data-tip="みんなの投稿">
            <%= link_to posts_path, class: "ml-auto btn btn-outline text-white bg-indigo-700 hover:bg-indigo-800" do %>
              <i class="fa-regular fa-comments fa-sm"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- モーダル -->
    <div class="text-left">
      <dialog id="new_post_modal" class="modal">
        <div class="modal-box">
          <form method="dialog">
            <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2" onclick="closeNewPostkModal()">✕</button>
          </form>
          <%= render 'posts/new' %>
        </div>
      </dialog>
    </div>

    <div class="mt-4">
      <% @private_posts.each do |post| %>
      <div class="p-4 my-2 bg-gray-50 rounded-lg shadow">
        <!-- タグと画像、本文を含む部分 -->
        <div class="flex flex-wrap gap-2 mb-4">
          <%= link_to post_path(post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "ml-auto btn btn-outline btn-sm" do %>
            <%= l post.created_at, format: :short %>
            <i class="fas fa-trash-alt ml-2"></i>
          <% end %>
        </div>
        <div class="flex flex-wrap gap-2 mb-4">
          <% post.tags.each do |tag| %>
            <span class="badge badge-primary badge-outline mr-2">
              <%= link_to items_search_path(keyword: tag.name)  do %>
                <%= tag.name %>
              <% end %>
            </span>
          <% end %>
          <% if post.drink_word.present? %>
            <span class="badge text-violet-700 badge-outline mr-2">
              <%= post.drink_word %>
            </span>
          <% end %>
        </div>
        <% if post.image.present? %>
          <div class="mb-4 flex justify-center">
            <%= image_tag post.image.url, alt: "#{post.image}の画像", class: "aspect-square w-50 h-50 object-cover rounded-lg" %>
          </div>
        <% end %>
        <div class="text-gray-700"><%= post.body %></div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="min-h-screen flex items-center justify-center bg-gray-100">
  <%= render "shared/loading" %>
  <div class="w-full max-w-2xl p-6 bg-white rounded-lg shadow-md">
    <div class="flex items-center space-x-4">
      <div class="flex-shrink-0">
        <%= image_tag @post.user.avatar.url, class: "w-12 h-12 rounded-full" %>
      </div>
      <div>
        <h2 class="text-xl font-semibold text-gray-800"><%= @post.user.name %> の投稿</h2>
        <time class="text-sm text-gray-500"><%= l @post.created_at, format: :short %></time>
      </div>
    </div>
    <div class="mt-4">
      <% @post.tags.each do |tag| %>
        <span class="inline-block bg-blue-200 text-blue-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded">
          <%= tag.name %>
        </span>
      <% end %>
    </div>
    <div class="mt-4 text-gray-700 text-lg">
      <%= @post.body %>
    </div>
  </div>
</div>